name: listview_cubit_hooks
description: A new Flutter project that demonstrates the usage of cubits, hooks and hive db storage.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.3 <3.0.0'
  flutter: '>=3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. To see which dependencies
#  have newer versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  easy_localization: ^3.0.1
  injectable: ^2.1.0
  auto_route: ^5.0.4
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  build_runner: 2.3.3
  injectable_generator: ^2.1.3
  auto_route_generator: ^5.0.3
  hive_generator: ^2.0.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/translations/
